name: percy test

on:
  push:
    branches:
      - master
      - svelte
  pull_request:
    branches:
      - master

jobs:
  visuals:
    runs-on: ubuntu-18.04
    steps:
    -  uses: actions/checkout@v2

    - name: Install deps
      run: npm install

    - name: Run app
      run: (npm run dev --host 0.0.0.0:500&)

    - name: Take snapshots
      run: npx percy snapshot snapshot.yml
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
